import type { ReactNode } from "react";
import Link from "next/link";

// Global styles:
import "@/styles/globals.css";
import "@typethings/ui/dist/index.css";
import { cn } from "@typethings/ui";

// Fonts:
import { Inter } from "next/font/google";
const InterFont = Inter({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  display: "swap",
  preload: true,
});

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-2xl px-4 py-10">
          <header>
            <div className="flex items-center justify-between">
              <nav className="ml-auto space-x-6 text-sm font-medium">
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
