import type { ReactNode } from "react";

// Global styles:
import "@/styles/globals.css";
import "@typethings/ui/dist/index.css";
import { cn } from "@typethings/ui";

// Providers:
import { ThemeProvider } from "@/providers/theme";

// Fonts:
import { Inter } from "next/font/google";
const interLatin = Inter({
  subsets: ["latin"],
  variable: "--inter-font",
  weight: ["400", "900"],
  display: "swap",
  preload: true,
});

// Analytics:
import { Analytics } from "@vercel/analytics/react";
import Header from "@/layout/header";

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen",
          `font-sans antialiased`,
          "bg-neutral-100 dark:bg-neutral-900",
          "text-neutral-900 dark:text-white",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main>{children}</main>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
